package com.tyshi00.aventura

// Generated quest pool, ported from the Soto app's quests.json, plus 34 additional
// MONTHLY-only quests to widen that tier's rotation pool (see README).
// 309 quests total spanning DAILY / WEEKLY / MONTHLY cadences.
object QuestPool {
    val all: List<Quest> = listOf(
        Quest(id = "find-older", title = "Find something older than you", description = "Find something in your home that's older than you are. Work out where it came from.", category = "Find", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "walk-block", title = "Loop your street", description = "Walk one full loop of your block. Phone stays home.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 15),
        Quest(id = "clear-surface", title = "Empty one surface", description = "Pick one table or shelf and clear it completely. Leave it empty.", category = "Fix", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "draw-room", title = "Draw the room", description = "Draw the room you're in. Don't fix the mistakes.", category = "Make", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "call-someone", title = "Call, don't text", description = "Call someone instead of texting them.", category = "Talk", tiers = listOf(QuestTier.DAILY), minutes = 15),
        Quest(id = "stairs", title = "Stairs, twice", description = "Find a set of stairs. Walk up and down them twice.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 5),
        Quest(id = "new-route", title = "Different way there", description = "Take a route you've never taken to somewhere you go often.", category = "Go", tiers = listOf(QuestTier.DAILY), minutes = 15),
        Quest(id = "handwrite", title = "Leave a note", description = "Write a note by hand and leave it where someone will find it.", category = "Write", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "read-paper", title = "Read on paper", description = "Read something printed for twenty minutes. Paper only.", category = "Read", tiers = listOf(QuestTier.DAILY, QuestTier.WEEKLY), minutes = 20),
        Quest(id = "cook-scratch", title = "Cook from scratch", description = "Make something to eat from raw ingredients. No shortcuts.", category = "Make", tiers = listOf(QuestTier.DAILY, QuestTier.WEEKLY), minutes = 45),
        Quest(id = "shoes-off", title = "Shoes off, outside", description = "Stand outside with your shoes off for two minutes.", category = "Go", tiers = listOf(QuestTier.DAILY), minutes = 5),
        Quest(id = "hear-list", title = "List what you hear", description = "Sit still and write down five things you can hear right now.", category = "Write", tiers = listOf(QuestTier.DAILY), minutes = 5),
        Quest(id = "give-away", title = "Box up ten things", description = "Find ten things you don't use. Box them up to give away.", category = "Fix", tiers = listOf(QuestTier.DAILY, QuestTier.WEEKLY), minutes = 20),
        Quest(id = "watch-sky", title = "Watch the sky", description = "Go outside and watch the sky until something in it changes.", category = "Look", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "fix-small", title = "Fix one broken thing", description = "Find one thing at home that's broken and fix it.", category = "Fix", tiers = listOf(QuestTier.DAILY, QuestTier.WEEKLY), minutes = 30),
        Quest(id = "stairs-today", title = "Skip the lift", description = "If you're able, take the stairs every time today. No lift, no escalator.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "stand-the-ride", title = "Stand the whole ride", description = "On the bus or train today, stand if you can. Leave the seat.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "walk-short-trip", title = "Walk the short one", description = "Any trip under two kilometres today, walk it instead of riding.", category = "Go", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "carry-it-home", title = "Carry it home", description = "Carry the shopping home by hand instead of driving.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "bike-one-trip", title = "One trip on foot", description = "Make one trip today by bike or on foot that you'd normally drive.", category = "Go", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "far-end", title = "Get off at the far end", description = "Stop, and get off at the furthest point and walk the rest.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "floor-tonight", title = "Floor, not sofa", description = "Sit on the floor this evening instead of the sofa.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "take-the-long-way", title = "Long way on purpose", description = "Walk the long way somewhere today. Add ten minutes.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "breathe-five", title = "Five minutes of breathing", description = "Sit still and breathe for five minutes. Count the breaths.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 5),
        Quest(id = "leave-better", title = "Leave it better", description = "Leave one place better than you found it.", category = "Fix", tiers = listOf(QuestTier.DAILY, QuestTier.WEEKLY), minutes = 0),
        Quest(id = "walk-new", title = "Walk somewhere new", description = "Walk for 45 minutes somewhere you've never been. No map.", category = "Go", tiers = listOf(QuestTier.WEEKLY, QuestTier.MONTHLY), minutes = 45),
        Quest(id = "write-review", title = "Review a place", description = "Write a review of a place you've been. Be specific.", category = "Write", tiers = listOf(QuestTier.WEEKLY), minutes = 20),
        Quest(id = "cook-for-someone", title = "Feed someone", description = "Cook a full meal and eat it with someone. No screens at the table.", category = "Make", tiers = listOf(QuestTier.WEEKLY), minutes = 60),
        Quest(id = "library", title = "Go to a library", description = "Go to a library or bookshop. Leave with one thing.", category = "Go", tiers = listOf(QuestTier.WEEKLY), minutes = 45),
        Quest(id = "learn-hands", title = "Learn a hand skill", description = "Learn one thing you do with your hands. A knot, a chord, a stitch. Practise until it sticks.", category = "Make", tiers = listOf(QuestTier.WEEKLY), minutes = 30),
        Quest(id = "long-walk", title = "Hour-long walk", description = "Walk for an hour with no destination and no headphones.", category = "Move", tiers = listOf(QuestTier.WEEKLY, QuestTier.MONTHLY), minutes = 60),
        Quest(id = "talk-stranger", title = "Talk to a stranger", description = "Have a real conversation with someone you don't usually talk to.", category = "Talk", tiers = listOf(QuestTier.WEEKLY), minutes = 20),
        Quest(id = "photo-five", title = "Five photos, no more", description = "Walk for an hour and take five photos. That's the limit. Make them count.", category = "Go", tiers = listOf(QuestTier.WEEKLY), minutes = 60),
        Quest(id = "get-in-water", title = "Get in the water", description = "Get into a river, lake, sea, or pool.", category = "Go", tiers = listOf(QuestTier.WEEKLY, QuestTier.MONTHLY), minutes = 45),
        Quest(id = "museum", title = "An afternoon at a museum", description = "Go to a museum or gallery. Find one thing you can stand in front of for ten minutes.", category = "Go", tiers = listOf(QuestTier.WEEKLY, QuestTier.MONTHLY), minutes = 90),
        Quest(id = "game-people", title = "Play a game with people", description = "Get people together for a game with no screen in it.", category = "Talk", tiers = listOf(QuestTier.WEEKLY), minutes = 60),
        Quest(id = "deep-clean", title = "Clean the parts you skip", description = "Pick one room and clean the parts you usually skip.", category = "Fix", tiers = listOf(QuestTier.WEEKLY), minutes = 60),
        Quest(id = "letter", title = "Post a letter", description = "Write a letter by hand and put it in the post.", category = "Write", tiers = listOf(QuestTier.WEEKLY, QuestTier.MONTHLY), minutes = 30),
        Quest(id = "new-cuisine", title = "Cook a new cuisine", description = "Cook a dish from a cuisine you've never made.", category = "Make", tiers = listOf(QuestTier.WEEKLY), minutes = 60),
        Quest(id = "sketch-place", title = "Draw what's in front of you", description = "Sit somewhere and draw what's in front of you for twenty minutes.", category = "Make", tiers = listOf(QuestTier.WEEKLY), minutes = 20),
        Quest(id = "live-event", title = "Go to something live", description = "Go to something live. Music, a match, a talk, a market.", category = "Go", tiers = listOf(QuestTier.WEEKLY, QuestTier.MONTHLY), minutes = 120),
        Quest(id = "plant", title = "Plant something", description = "Plant something and set a place to keep it alive.", category = "Fix", tiers = listOf(QuestTier.WEEKLY, QuestTier.MONTHLY), minutes = 45),
        Quest(id = "overnight", title = "Sleep somewhere new", description = "Spend a night somewhere you've never stayed.", category = "Go", tiers = listOf(QuestTier.MONTHLY), minutes = 0),
        Quest(id = "stars", title = "Find a constellation", description = "Get away from city light and find one constellation you can name.", category = "Go", tiers = listOf(QuestTier.MONTHLY), minutes = 60),
        Quest(id = "high-view", title = "Climb to a high point", description = "Climb to the highest point you can reach. Look back at where you started.", category = "Go", tiers = listOf(QuestTier.MONTHLY), minutes = 120),
        Quest(id = "volunteer", title = "Give half a day", description = "Give half a day to something that needs hands. In person.", category = "Talk", tiers = listOf(QuestTier.MONTHLY), minutes = 240),
        Quest(id = "host", title = "Cook for friends", description = "Have people over and cook for them. Phones in a pile by the door.", category = "Make", tiers = listOf(QuestTier.MONTHLY), minutes = 180),
        Quest(id = "day-offline", title = "A day with the phone off", description = "Pick one day this month with the phone off. Tell people first.", category = "Go", tiers = listOf(QuestTier.MONTHLY), minutes = 0),
        Quest(id = "new-area", title = "Get lost on purpose", description = "Spend an afternoon lost on purpose in a part of town you don't know.", category = "Go", tiers = listOf(QuestTier.MONTHLY), minutes = 120),
        Quest(id = "make-gift", title = "Make a gift", description = "Make something by hand and give it to someone in person.", category = "Make", tiers = listOf(QuestTier.MONTHLY), minutes = 120),
        Quest(id = "old-contact", title = "Reach an old contact", description = "Reach out to someone you've lost touch with. Meet up or call.", category = "Talk", tiers = listOf(QuestTier.MONTHLY), minutes = 60),
        Quest(id = "nature-day", title = "A full day outside", description = "Give a full day to a forest, coast, or mountain. Come home tired.", category = "Go", tiers = listOf(QuestTier.MONTHLY), minutes = 0),
        Quest(id = "finish-book", title = "Finish a book", description = "Read one book cover to cover this month.", category = "Read", tiers = listOf(QuestTier.MONTHLY), minutes = 0),
        Quest(id = "teach", title = "Teach someone", description = "Teach someone a thing you know. Face to face.", category = "Talk", tiers = listOf(QuestTier.MONTHLY), minutes = 60),
        Quest(id = "ap-window-name", title = "Name what's out there", description = "Watch out the window until you see something you can't name. Guess what it is.", category = "Look", tiers = listOf(), minutes = 10),
        Quest(id = "ap-letter-future", title = "Letter to yourself", description = "Write a letter to yourself to read in a year. Seal it when you land.", category = "Write", tiers = listOf(), minutes = 20),
        Quest(id = "ap-plan-trip", title = "Plan the next trip", description = "Plan your next trip on paper. Where, when, who.", category = "Write", tiers = listOf(), minutes = 20),
        Quest(id = "ap-list-fix", title = "List ten fixes", description = "List ten things at home you've meant to fix. Mark the one you'll do first.", category = "Write", tiers = listOf(), minutes = 15),
        Quest(id = "ap-stretch", title = "Shoulders and ankles", description = "Roll your shoulders and ankles slowly. Ten each.", category = "Move", tiers = listOf(), minutes = 5),
        Quest(id = "ap-draw-tray", title = "Draw the tray table", description = "Draw whatever's on your tray table. Badly is fine.", category = "Make", tiers = listOf(), minutes = 15),
        Quest(id = "ap-backstory", title = "Invent a backstory", description = "Pick a stranger nearby. Decide where they're going and why. Write it down.", category = "Write", tiers = listOf(), minutes = 15),
        Quest(id = "ap-three-pages", title = "Three pages about nothing", description = "Write three pages about nothing in particular. Don't stop to read them.", category = "Write", tiers = listOf(), minutes = 20),
        Quest(id = "ap-recall-day", title = "Write down a day", description = "Pick a day you remember well. Write it out in as much detail as you can.", category = "Write", tiers = listOf(), minutes = 20),
        Quest(id = "ap-ten-words", title = "Ten words of a language", description = "Learn ten words of a language you don't speak. Use the seatback card or your memory.", category = "Read", tiers = listOf(), minutes = 15),
        Quest(id = "ap-chapter", title = "Read one chapter", description = "Read one chapter of a book. Paper or downloaded, no feed.", category = "Read", tiers = listOf(), minutes = 20),
        Quest(id = "ap-problem-page", title = "Solve it on paper", description = "Write down a problem you have. Fill the page with ways to solve it.", category = "Write", tiers = listOf(), minutes = 15),
        Quest(id = "ap-meal-list", title = "Plan a meal to cook", description = "Plan a meal you'll cook when you land. Write the list.", category = "Write", tiers = listOf(), minutes = 10),
        Quest(id = "ap-map-memory", title = "Map from memory", description = "Draw a map of your neighbourhood from memory. Check it later.", category = "Make", tiers = listOf(), minutes = 15),
        Quest(id = "ap-count-window", title = "Count from the window", description = "Count the lakes, roads, or towns you can spot from the window.", category = "Look", tiers = listOf(), minutes = 10),
        Quest(id = "ap-letter-someone", title = "Write to someone", description = "Write a letter to someone. Decide later whether to send it.", category = "Write", tiers = listOf(), minutes = 20),
        Quest(id = "press-ups", title = "Press-ups, one go", description = "Do as many press-ups as you can in one go. Remember the number.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "squats-20", title = "Twenty squats", description = "Do twenty squats. Slow on the way down.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "plank-hold", title = "Hold a plank", description = "Hold a plank until you have to stop.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "dance-one", title = "Dance to one song", description = "Play one song and dance to the whole thing.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 5),
        Quest(id = "balance-head", title = "Balance and cross the room", description = "Balance an object on your head and cross the room.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 5),
        Quest(id = "one-leg-brush", title = "Brush on one leg", description = "Stand on one leg the whole time you brush your teeth.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "reach-toes", title = "Reach your toes", description = "Touch your toes ten times. Keep your knees straight.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "walk-30", title = "Thirty minutes on foot", description = "Walk for thirty minutes with nowhere to be.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 30),
        Quest(id = "jog-ten", title = "Run ten minutes", description = "Run for ten minutes, however slowly.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "skip-three", title = "Skip for three minutes", description = "Skip on the spot for three minutes.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 5),
        Quest(id = "wall-sit", title = "Sit on a wall, no chair", description = "Sit against a wall with no chair for as long as you can.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "carry-heavy", title = "Carry something heavy", description = "Carry something heavy across the room ten times.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 5),
        Quest(id = "climb-nearest-hill", title = "Top of the nearest hill", description = "Walk to the top of the nearest high ground.", category = "Go", tiers = listOf(QuestTier.DAILY), minutes = 30),
        Quest(id = "stretch-floor", title = "Stretch on the floor", description = "Lie on the floor and stretch out for five minutes.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 5),
        Quest(id = "jumping-jacks", title = "Fifty star jumps", description = "Do fifty star jumps. Stop and start if you need to.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 5),
        Quest(id = "walk-til-tired", title = "Walk until your legs complain", description = "Walk one way until your legs complain, then walk back.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 45),
        Quest(id = "crawl-room", title = "Crawl a room", description = "Get down and crawl the length of a room. Notice what's down there.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 5),
        Quest(id = "hang-bar", title = "Hang until you drop", description = "Hang from something sturdy for as long as your grip lasts.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "backwards-walk", title = "Walk it backwards", description = "Walk backwards across a room ten times. Safely.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 5),
        Quest(id = "shadow-box", title = "Box the air", description = "Throw punches at the air for two minutes.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 5),
        Quest(id = "watch-birds", title = "Tell two birds apart", description = "Watch birds until you can tell two kinds apart.", category = "Look", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "hand-on-tree", title = "Age a tree", description = "Put your hand on a tree and guess its age.", category = "Find", tiers = listOf(QuestTier.DAILY), minutes = 5),
        Quest(id = "follow-insect", title = "Follow an insect", description = "Find an insect and follow it until it loses you.", category = "Look", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "bare-feet-grass", title = "Bare feet on grass", description = "Stand on grass with bare feet for two minutes.", category = "Go", tiers = listOf(QuestTier.DAILY), minutes = 5),
        Quest(id = "out-in-rain", title = "Out in the rain", description = "When it next rains, stand in it for a minute.", category = "Go", tiers = listOf(QuestTier.DAILY), minutes = 5),
        Quest(id = "find-the-moon", title = "Read the moon", description = "Find the moon and work out if it's growing or shrinking.", category = "Look", tiers = listOf(QuestTier.DAILY), minutes = 5),
        Quest(id = "five-litter", title = "Five pieces of litter", description = "Pick up five pieces of litter on your way somewhere.", category = "Fix", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "sit-in-park", title = "Ten minutes in a park", description = "Sit in a park and do nothing for ten minutes.", category = "Go", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "find-moss", title = "Find moss", description = "Find moss growing somewhere and look at it up close.", category = "Find", tiers = listOf(QuestTier.DAILY), minutes = 5),
        Quest(id = "watch-sunset", title = "Whole sunset", description = "Watch the sun go down from start to finish.", category = "Look", tiers = listOf(QuestTier.DAILY), minutes = 20),
        Quest(id = "name-three-birds", title = "Name three birds", description = "Name three birds you can see or hear. Look up the ones you can't.", category = "Find", tiers = listOf(QuestTier.DAILY), minutes = 15),
        Quest(id = "collect-leaves", title = "Three different leaves", description = "Collect three different leaves and lay them out.", category = "Find", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "find-running-water", title = "Listen to moving water", description = "Find moving water and listen to it for five minutes.", category = "Go", tiers = listOf(QuestTier.DAILY), minutes = 15),
        Quest(id = "watch-ants", title = "Both ends of an ant trail", description = "Find an ant trail and follow it to both ends.", category = "Look", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "smell-five", title = "Five things worth smelling", description = "Go outside and find five things worth smelling.", category = "Find", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "cloud-shapes", title = "Watch the clouds", description = "Lie back and watch the clouds until one becomes something.", category = "Look", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "find-web", title = "Find a spider's web", description = "Find a spider's web and look at how it's built.", category = "Find", tiers = listOf(QuestTier.DAILY), minutes = 5),
        Quest(id = "skim-stones", title = "Stones on water", description = "Find water and skim or drop stones into it.", category = "Go", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "climb-tree-look", title = "Up a tree", description = "Climb a tree, even a low one, and look around from up there.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 15),
        Quest(id = "watch-stars-ten", title = "Ten minutes of stars", description = "Stand outside at night and watch the stars for ten minutes.", category = "Look", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "find-wildflower", title = "A flower no one planted", description = "Find a wild flower growing where no one planted it.", category = "Find", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "listen-dawn", title = "Listen to the morning", description = "Get up early and listen to the morning before the traffic.", category = "Look", tiers = listOf(QuestTier.DAILY), minutes = 15),
        Quest(id = "feel-bark", title = "Three kinds of bark", description = "Find three trees with different bark and feel each one.", category = "Find", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "watch-water-15", title = "Watch water", description = "If you're near water, watch it for fifteen minutes.", category = "Look", tiers = listOf(QuestTier.DAILY), minutes = 15),
        Quest(id = "find-bug-home", title = "Where the bugs live", description = "Find where insects live and leave it as you found it.", category = "Find", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "wipe-one-window", title = "One clear window", description = "Clean one window until it's clear.", category = "Fix", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "water-all-plants", title = "Water every plant", description = "Water every plant in the house.", category = "Fix", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "sew-button", title = "Sew a button back on", description = "Sew a loose button back on properly.", category = "Fix", tiers = listOf(QuestTier.DAILY), minutes = 15),
        Quest(id = "polish-shoes", title = "Polish a pair of shoes", description = "Polish a pair of shoes until they shine.", category = "Fix", tiers = listOf(QuestTier.DAILY), minutes = 15),
        Quest(id = "descale-kettle", title = "Descale the kettle", description = "Descale the kettle or clean the coffee maker.", category = "Fix", tiers = listOf(QuestTier.DAILY), minutes = 15),
        Quest(id = "oil-hinge", title = "Silence a hinge", description = "Find a squeaking hinge and oil it.", category = "Fix", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "sort-drawer", title = "Sort one drawer", description = "Empty a drawer, bin the junk, put the rest back tidy.", category = "Fix", tiers = listOf(QuestTier.DAILY), minutes = 15),
        Quest(id = "make-bed-properly", title = "Make the bed properly", description = "Strip the bed and make it properly with clean sheets.", category = "Fix", tiers = listOf(QuestTier.DAILY), minutes = 15),
        Quest(id = "dust-high", title = "Dust where you never reach", description = "Dust the places you never reach.", category = "Fix", tiers = listOf(QuestTier.DAILY), minutes = 15),
        Quest(id = "sharpen-pencils", title = "Sharpen every pencil", description = "Sharpen every pencil in the house.", category = "Fix", tiers = listOf(QuestTier.DAILY), minutes = 5),
        Quest(id = "tighten-screw", title = "Tighten what's loose", description = "Find a loose screw or handle and tighten it.", category = "Fix", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "clean-outdoor-shoes", title = "Clean your shoes", description = "Clean the mud off your outdoor shoes.", category = "Fix", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "set-the-clocks", title = "Set every clock right", description = "Set every clock in the house to the right time.", category = "Fix", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "declutter-ten", title = "Ten things out", description = "Find ten things you don't need and set them aside.", category = "Fix", tiers = listOf(QuestTier.DAILY), minutes = 15),
        Quest(id = "scrub-pan", title = "Scrub the bad pan", description = "Scrub the pan you've been avoiding.", category = "Fix", tiers = listOf(QuestTier.DAILY), minutes = 15),
        Quest(id = "tidy-cables", title = "Tame the cables", description = "Untangle and tidy the cables behind something.", category = "Fix", tiers = listOf(QuestTier.DAILY), minutes = 15),
        Quest(id = "clean-mirror", title = "Clean a mirror", description = "Clean a mirror and the frame around it.", category = "Fix", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "empty-your-bag", title = "Empty the bag you carry", description = "Empty out a bag you carry and only put back what you use.", category = "Fix", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "fold-laundry", title = "Fold and put away", description = "Fold a pile of laundry and put it all away.", category = "Fix", tiers = listOf(QuestTier.DAILY), minutes = 15),
        Quest(id = "sweep-doorstep", title = "Sweep the doorstep", description = "Sweep the doorstep and the path to it.", category = "Fix", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "draw-your-hand", title = "Draw your hand", description = "Draw your own hand without looking at the paper.", category = "Make", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "write-haiku", title = "Write a haiku", description = "Write a haiku about whatever's in front of you.", category = "Write", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "fold-paper-stand", title = "Fold paper that stands", description = "Fold a piece of paper into something that stands up.", category = "Make", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "build-from-junk", title = "Build from the recycling", description = "Build something small from things in the recycling.", category = "Make", tiers = listOf(QuestTier.DAILY), minutes = 20),
        Quest(id = "photo-one-thing", title = "One photo, then away", description = "Take one photograph of one thing, then put the phone away.", category = "Make", tiers = listOf(QuestTier.DAILY), minutes = 5),
        Quest(id = "cook-no-recipe", title = "Cook with no recipe", description = "Cook something with no recipe, using what's in the cupboard.", category = "Make", tiers = listOf(QuestTier.DAILY), minutes = 30),
        Quest(id = "write-postcard", title = "Write a postcard", description = "Write a postcard to someone, even if you hand it to them.", category = "Write", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "doodle-page", title = "Fill a page with doodles", description = "Fill a page with doodles and don't plan them.", category = "Make", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "build-tower", title = "Tallest tower you can", description = "Build the tallest stable tower you can from what's nearby.", category = "Make", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "draw-your-door", title = "Draw your front door", description = "Draw the front of your home from memory.", category = "Make", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "invent-sandwich", title = "Invent a sandwich", description = "Invent a sandwich you've never made and eat it.", category = "Make", tiers = listOf(QuestTier.DAILY), minutes = 15),
        Quest(id = "paper-plane", title = "Fly a paper plane", description = "Make a paper plane and fly it as far as you can.", category = "Make", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "list-ten-good", title = "Ten things that held up", description = "Write a list of ten things that made today bearable.", category = "Write", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "trace-shadow", title = "Trace a shadow", description = "Trace the shadow of an object onto paper.", category = "Make", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "carve-soap", title = "Carve a bar of soap", description = "Carve something out of a bar of soap.", category = "Make", tiers = listOf(QuestTier.DAILY), minutes = 20),
        Quest(id = "call-relative", title = "Call a relative", description = "Call a relative you haven't spoken to in a while.", category = "Talk", tiers = listOf(QuestTier.DAILY), minutes = 20),
        Quest(id = "thank-someone", title = "Thank someone properly", description = "Thank someone properly for something they did.", category = "Talk", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "compliment-stranger", title = "Compliment a stranger", description = "Give a stranger an honest compliment.", category = "Talk", tiers = listOf(QuestTier.DAILY), minutes = 5),
        Quest(id = "ask-neighbour", title = "Ask a neighbour how they are", description = "Ask a neighbour how they are and mean it.", category = "Talk", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "share-food", title = "Give food away", description = "Make too much food and give some away.", category = "Talk", tiers = listOf(QuestTier.DAILY), minutes = 30),
        Quest(id = "eat-with-someone", title = "Eat with someone, no phones", description = "Eat one meal today with someone, no phones out.", category = "Talk", tiers = listOf(QuestTier.DAILY), minutes = 30),
        Quest(id = "ask-elder", title = "Ask about back then", description = "Ask an older person to tell you about when they were young.", category = "Talk", tiers = listOf(QuestTier.DAILY), minutes = 30),
        Quest(id = "introduce-yourself", title = "Learn a name", description = "Introduce yourself to someone whose name you don't know.", category = "Talk", tiers = listOf(QuestTier.DAILY), minutes = 5),
        Quest(id = "write-thanks-note", title = "A thank-you by hand", description = "Write a thank-you note by hand and give it.", category = "Write", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "offer-help", title = "Offer a hand", description = "Offer to help someone carry, lift, or fix something.", category = "Talk", tiers = listOf(QuestTier.DAILY), minutes = 15),
        Quest(id = "count-windows", title = "Count the windows", description = "Count the windows on the front of your building.", category = "Find", tiers = listOf(QuestTier.DAILY), minutes = 5),
        Quest(id = "find-oldest-building", title = "The oldest building near you", description = "Find the oldest building near you and read up on it later.", category = "Find", tiers = listOf(QuestTier.DAILY), minutes = 20),
        Quest(id = "read-a-plaque", title = "Read the plaque", description = "Find a plaque or sign you've walked past and actually read it.", category = "Read", tiers = listOf(QuestTier.DAILY), minutes = 5),
        Quest(id = "read-poem-aloud", title = "Read a poem out loud", description = "Read a poem out loud to the room.", category = "Read", tiers = listOf(QuestTier.DAILY), minutes = 5),
        Quest(id = "learn-one-word", title = "Learn one word", description = "Learn one word you don't know and use it today.", category = "Read", tiers = listOf(QuestTier.DAILY), minutes = 5),
        Quest(id = "read-paper-map", title = "Trace a route on paper", description = "Find a paper map and trace a route on it.", category = "Read", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "memorise-four-lines", title = "Learn four lines", description = "Memorise four lines of a poem or song.", category = "Read", tiers = listOf(QuestTier.DAILY), minutes = 15),
        Quest(id = "find-ten-red", title = "Ten red things", description = "Find ten red things on a short walk.", category = "Find", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "watch-light-change", title = "Watch the light change", description = "Watch the sky until the light changes.", category = "Look", tiers = listOf(QuestTier.DAILY), minutes = 15),
        Quest(id = "trace-street-name", title = "Where the name comes from", description = "Pick a street near you and find out where its name comes from.", category = "Find", tiers = listOf(QuestTier.DAILY), minutes = 15),
        Quest(id = "shake-it-out", title = "Shake it out", description = "Shake out your arms, your legs, a rug, a doormat. Anything that needs it.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 5),
        Quest(id = "wake-up-stretch", title = "Wake-up stretch", description = "Do the big stretch you'd do first thing in the morning. The real one.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "make-yourself-dizzy", title = "Make yourself dizzy", description = "Spin until the room moves. Don't fall over.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "hop-the-length-of-the-room", title = "Hop the length of the room", description = "Hop on one leg from one end of the room to the other.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "do-a-forward-roll", title = "Do a forward roll", description = "Find a soft spot and do a forward roll, like you used to.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "balance-eyes-shut", title = "Balance, eyes shut", description = "Balance on one leg with your eyes shut. Time it.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "silly-walk-down-the-hall", title = "Silly walk down the hall", description = "Do your best silly walk from one room to the next.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "balance-a-spoon-on-your-nose", title = "Balance a spoon on your nose", description = "Balance a spoon on your nose for as long as you can.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "tightrope-the-floor", title = "Tightrope the floor", description = "Pick a line on the floor and walk it heel to toe without wobbling.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "crab-walk-a-lap", title = "Crab walk a lap", description = "Crab walk one lap of the room. Try not to laugh.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "balance-on-the-back-of-your-hand", title = "Balance on the back of your hand", description = "Balance something on the back of your hand and walk a lap of the room.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 5),
        Quest(id = "balance-on-your-knee", title = "Balance on your knee", description = "Balance an object on your knee and hold it steady. Count to twenty.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 5),
        Quest(id = "balance-on-your-foot", title = "Balance on your foot", description = "Balance something on your foot without letting it drop.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 5),
        Quest(id = "balance-on-one-finger", title = "Balance on one finger", description = "Balance something on one fingertip for as long as you can.", category = "Move", tiers = listOf(QuestTier.DAILY), minutes = 5),
        Quest(id = "make-a-posh-hot-drink", title = "Make a posh hot drink", description = "Make the fanciest hot drink you can with what's in.", category = "Make", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "try-a-new-fruit", title = "Try a new fruit", description = "Buy one fruit you've never eaten and eat it.", category = "Find", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "bake-something-easy", title = "Bake something easy", description = "Bake something simple and eat it warm.", category = "Make", tiers = listOf(QuestTier.DAILY), minutes = 45),
        Quest(id = "a-tiny-picnic", title = "A tiny picnic", description = "Take a snack outside and have a little picnic.", category = "Go", tiers = listOf(QuestTier.DAILY), minutes = 20),
        Quest(id = "eat-outside", title = "Eat outside", description = "Take a meal outside and eat it there.", category = "Go", tiers = listOf(QuestTier.DAILY), minutes = 20),
        Quest(id = "a-playlist-by-hand", title = "A playlist by hand", description = "Write out a perfect playlist on paper, then play it.", category = "Make", tiers = listOf(QuestTier.DAILY), minutes = 15),
        Quest(id = "reread-a-favourite-page", title = "Reread a favourite page", description = "Find a book you love and reread your favourite bit.", category = "Read", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "blow-bubbles", title = "Blow bubbles", description = "Make some bubbles and chase them about.", category = "Make", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "fly-a-kite", title = "Fly a kite", description = "Get a kite up, shop-bought or homemade.", category = "Go", tiers = listOf(QuestTier.DAILY), minutes = 30),
        Quest(id = "feed-the-ducks", title = "Feed the ducks", description = "Take some seed to a pond and feed whatever's there.", category = "Go", tiers = listOf(QuestTier.DAILY), minutes = 20),
        Quest(id = "coffee-out-no-phone", title = "Coffee out, no phone", description = "Take yourself out for a coffee and sit with no phone.", category = "Go", tiers = listOf(QuestTier.DAILY), minutes = 20),
        Quest(id = "lunch-out-on-your-own", title = "Lunch out, on your own", description = "Eat lunch in a cafe on your own. No screen, just the food.", category = "Go", tiers = listOf(QuestTier.DAILY), minutes = 30),
        Quest(id = "a-book-and-a-drink", title = "A book and a drink", description = "Take a book to a cafe or bar and read it over a drink.", category = "Go", tiers = listOf(QuestTier.DAILY), minutes = 30),
        Quest(id = "browse-a-bookshop", title = "Browse a bookshop", description = "Browse a bookshop on your own with no plan to buy.", category = "Go", tiers = listOf(QuestTier.DAILY), minutes = 20),
        Quest(id = "draw-your-hand-one-line", title = "Draw your hand, one line", description = "Draw your own hand without lifting the pen off the paper.", category = "Make", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "write-a-daft-limerick", title = "Write a daft limerick", description = "Write a daft limerick about your day.", category = "Write", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "review-your-own-kitchen", title = "Review your own kitchen", description = "Write a mock review of your own kitchen. Stars and all.", category = "Write", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "hide-a-message", title = "Hide a message", description = "Write a secret message and hide it for someone to find.", category = "Write", tiers = listOf(QuestTier.DAILY), minutes = 10),
        Quest(id = "build-a-card-tower", title = "Build a card tower", description = "Build the tallest tower of cards you can.", category = "Make", tiers = listOf(QuestTier.DAILY), minutes = 15),
        Quest(id = "take-yourself-to-dinner", title = "Take yourself to dinner", description = "Take yourself out to dinner, alone. No phone at the table.", category = "Go", tiers = listOf(QuestTier.WEEKLY), minutes = 90),
        Quest(id = "a-film-on-your-own", title = "A film on your own", description = "Go to the cinema on your own.", category = "Go", tiers = listOf(QuestTier.WEEKLY), minutes = 120),
        Quest(id = "a-gallery-on-your-own", title = "A gallery on your own", description = "Go to a gallery or museum on your own and take your time.", category = "Go", tiers = listOf(QuestTier.WEEKLY), minutes = 90),
        Quest(id = "live-music-solo", title = "Live music, solo", description = "Go to live music on your own.", category = "Go", tiers = listOf(QuestTier.WEEKLY), minutes = 120),
        Quest(id = "an-afternoon-at-a-historic-site", title = "An afternoon at a historic site", description = "Spend an afternoon at a historic site. Work out what it means without using your phone.", category = "Go", tiers = listOf(QuestTier.WEEKLY), minutes = 120),
        Quest(id = "build-a-sandcastle", title = "Build a sandcastle", description = "Find sand and build something daft. Bucket optional.", category = "Make", tiers = listOf(QuestTier.WEEKLY), minutes = 45),
        Quest(id = "have-a-picnic", title = "Have a picnic", description = "Pack a picnic and eat it somewhere with a view.", category = "Go", tiers = listOf(QuestTier.WEEKLY), minutes = 90),
        Quest(id = "ice-cream-somewhere-new", title = "Ice cream somewhere new", description = "Walk or ride somewhere new for an ice cream.", category = "Go", tiers = listOf(QuestTier.WEEKLY), minutes = 60),
        Quest(id = "bake-a-cake-for-no-reason", title = "Bake a cake for no reason", description = "Bake a cake with no occasion and share it.", category = "Make", tiers = listOf(QuestTier.WEEKLY), minutes = 90),
        Quest(id = "mooch-round-a-market", title = "Mooch round a market", description = "Spend a morning mooching a market with no shopping list.", category = "Go", tiers = listOf(QuestTier.WEEKLY), minutes = 90),
        Quest(id = "an-hour-of-bird-watching", title = "An hour of bird watching", description = "Take an hour to watch birds and name what you can.", category = "Look", tiers = listOf(QuestTier.WEEKLY), minutes = 60),
        Quest(id = "bowling-or-mini-golf", title = "Bowling or mini-golf", description = "Go bowling or play mini-golf with someone.", category = "Go", tiers = listOf(QuestTier.WEEKLY), minutes = 90),
        Quest(id = "an-afternoon-at-an-aquarium", title = "An afternoon at an aquarium", description = "Spend an afternoon at an aquarium or planetarium.", category = "Go", tiers = listOf(QuestTier.WEEKLY), minutes = 120),
        Quest(id = "try-a-class-once", title = "Try a class once", description = "Drop into a class you've never tried, just the once.", category = "Make", tiers = listOf(QuestTier.WEEKLY), minutes = 90),
        Quest(id = "a-wander-with-a-camera", title = "A wander with a camera", description = "Take an hour to wander and shoot ten photos, no more.", category = "Make", tiers = listOf(QuestTier.WEEKLY), minutes = 60),
        Quest(id = "watch-a-sunrise-somewhere", title = "Watch a sunrise somewhere", description = "Get to a good spot and watch the sun come up.", category = "Look", tiers = listOf(QuestTier.WEEKLY), minutes = 60),
        Quest(id = "camp-a-night", title = "Camp a night", description = "Spend a night under canvas or stars. The garden counts.", category = "Go", tiers = listOf(QuestTier.MONTHLY), minutes = 0),
        Quest(id = "catch-a-meteor-shower", title = "Catch a meteor shower", description = "Find out when the next one is, get dark sky, and watch.", category = "Look", tiers = listOf(QuestTier.MONTHLY), minutes = 90),
        Quest(id = "go-to-a-festival-or-fair", title = "Go to a festival or fair", description = "Spend a day at a festival, fair, or show.", category = "Go", tiers = listOf(QuestTier.MONTHLY), minutes = 0),
        Quest(id = "go-to-the-theatre", title = "Go to the theatre", description = "See a play, a panto, or a show.", category = "Go", tiers = listOf(QuestTier.MONTHLY), minutes = 150),
        Quest(id = "go-fishing", title = "Go fishing", description = "Spend a morning trying to catch a fish.", category = "Go", tiers = listOf(QuestTier.MONTHLY), minutes = 180),
        Quest(id = "go-rockpooling", title = "Go rockpooling", description = "Spend low tide poking about in rockpools.", category = "Find", tiers = listOf(QuestTier.MONTHLY), minutes = 120),
        Quest(id = "host-a-games-night", title = "Host a games night", description = "Host a games night with no screen in the room.", category = "Talk", tiers = listOf(QuestTier.MONTHLY), minutes = 180),
        Quest(id = "have-a-bonfire", title = "Have a bonfire", description = "Build a fire where you're allowed and sit with it into the dark.", category = "Go", tiers = listOf(QuestTier.MONTHLY), minutes = 0),
        Quest(id = "join-a-parkrun", title = "Join a parkrun", description = "Join a free local run and go at your own pace.", category = "Move", tiers = listOf(QuestTier.MONTHLY), minutes = 60),
        Quest(id = "a-day-trip-by-train", title = "A day trip by train", description = "Take a train somewhere just for the day.", category = "Go", tiers = listOf(QuestTier.MONTHLY), minutes = 0),
        Quest(id = "a-weekend-by-the-sea", title = "A weekend by the sea", description = "Spend a weekend at the coast. Travel slow.", category = "Go", tiers = listOf(QuestTier.MONTHLY), minutes = 0),
        Quest(id = "a-weekend-in-the-hills", title = "A weekend in the hills", description = "Spend a weekend in the hills. Travel slow.", category = "Go", tiers = listOf(QuestTier.MONTHLY), minutes = 0),
        Quest(id = "stay-with-a-friend", title = "Stay with a friend", description = "Go and stay a night or two with a friend who lives elsewhere.", category = "Talk", tiers = listOf(QuestTier.MONTHLY), minutes = 0),
        Quest(id = "a-bike-adventure", title = "A bike adventure", description = "Plan a bike ride somewhere new and pack a snack.", category = "Go", tiers = listOf(QuestTier.MONTHLY), minutes = 0),
        Quest(id = "see-live-comedy", title = "See live comedy", description = "Go to a comedy night and laugh in a room full of strangers.", category = "Go", tiers = listOf(QuestTier.MONTHLY), minutes = 120),
        Quest(id = "learn-a-party-trick", title = "Learn a party trick", description = "Learn one thing you can show off at a party.", category = "Make", tiers = listOf(QuestTier.MONTHLY), minutes = 0),
        Quest(id = "make-jam-or-pickles", title = "Make jam or pickles", description = "Make something you can keep in a jar.", category = "Make", tiers = listOf(QuestTier.MONTHLY), minutes = 120),
        Quest(id = "buy-nothing-today", title = "Buy nothing today", description = "Get through today buying nothing. Essentials aside.", category = "Find", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "two-no-spend-days", title = "Two no-spend days", description = "Have two no-spend days this week. Nothing but essentials.", category = "Find", tiers = listOf(QuestTier.WEEKLY), minutes = 0),
        Quest(id = "a-no-spend-week", title = "A no-spend week", description = "Take one week this month and buy nothing but essentials.", category = "Find", tiers = listOf(QuestTier.MONTHLY), minutes = 0),
        Quest(id = "watch-it-arrive", title = "Watch it arrive", description = "Get outside before the sun's properly up. Watch it arrive.", category = "Go", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "lunch-outside", title = "Lunch outside", description = "Take your lunch outside. Eat it slow, no screen.", category = "Go", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "hands-for-twenty-minutes", title = "Hands for twenty minutes", description = "Make something with your hands for twenty minutes.", category = "Make", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "catch-the-last-of-the-sun", title = "Catch the last of the sun", description = "Find a doorway facing the sunset and watch it go.", category = "Look", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "find-one-star", title = "Find one star", description = "Find one star you can name. If the sky's no good, find the moon.", category = "Look", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "listen-in-the-dark", title = "Listen in the dark", description = "Make the room dark, lie down, and listen until you can hear five things.", category = "Look", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "take-the-next-turning", title = "Take the next turning", description = "Take the next turning you've never taken. See where it goes.", category = "Go", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "invent-a-life", title = "Invent a life", description = "Look up from the seat. Pick a stranger and invent where they're going.", category = "Write", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "somewhere-that-needs-a-map", title = "Somewhere that needs a map", description = "Go somewhere for the day that needs a map.", category = "Go", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "five-on-the-doorstep", title = "Five on the doorstep", description = "Sit on the doorstep for five minutes. That's the whole quest.", category = "Go", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "until-your-ears-are-cold", title = "Until your ears are cold", description = "Wrap up, go out, and come back when your ears are cold.", category = "Go", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "until-the-streetlights", title = "Until the streetlights", description = "Stay out until the streetlights come on.", category = "Go", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "name-a-cloud", title = "Name a cloud", description = "Find a cloud out the window and give it a name.", category = "Look", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "guess-where-you-are", title = "Guess where you are", description = "Look down out of the window and guess which country you're over.", category = "Find", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "stay-for-the-cold-air", title = "Stay for the cold air", description = "Step outside just for the cold air. One minute.", category = "Go", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "morning-no-screen", title = "Morning, no screen", description = "First hour awake, keep the phone down. Make tea, look out.", category = "Look", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "follow-something", title = "Follow something.", description = "", category = "", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "make-a-detour", title = "Make a detour.", description = "", category = "", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "leave-it-better-than-you-found-it", title = "Leave it better than you found it.", description = "", category = "", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "go-the-wrong-way-on-purpose", title = "Go the wrong way on purpose.", description = "", category = "", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "look-up", title = "Look up.", description = "", category = "", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "find-water", title = "Find water.", description = "", category = "", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "take-the-long-way-2", title = "Take the long way.", description = "", category = "", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "talk-to-someone-you-d-usually-just-nod-at", title = "Talk to someone you'd usually just nod at.", description = "", category = "", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "do-the-thing-you-keep-walking-past", title = "Do the thing you keep walking past.", description = "", category = "", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "find-a-door-you-ve-never-been-through", title = "Find a door you've never been through.", description = "", category = "", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "go-where-it-s-quiet", title = "Go where it's quiet.", description = "", category = "", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "collect-three-things-worth-keeping", title = "Collect three things worth keeping.", description = "", category = "", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "trace-something-back-to-where-it-started", title = "Trace something back to where it started.", description = "", category = "", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "waste-an-hour-well", title = "Waste an hour well.", description = "", category = "", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "find-the-edge-of-where-you-know-then-step-past-i", title = "Find the edge of where you know, then step past it.", description = "", category = "", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "do-something-a-child-would-do", title = "Do something a child would do.", description = "", category = "", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "make-something-out-of-nothing", title = "Make something out of nothing.", description = "", category = "", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "put-one-thing-right", title = "Put one thing right.", description = "", category = "", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "give-something-away", title = "Give something away.", description = "", category = "", tiers = listOf(QuestTier.DAILY), minutes = 0),
        Quest(id = "get-your-hands-dirty", title = "Get your hands dirty.", description = "", category = "", tiers = listOf(QuestTier.DAILY), minutes = 0),

    // ── 34 additional MONTHLY-only quests (not in DAILY or WEEKLY) ──────────
        Quest(id = "visit-farmers-market", title = "Visit a farmers market", description = "Go to a farmers market and ask one grower about what they're selling.", category = "Talk", tiers = listOf(QuestTier.MONTHLY), minutes = 60),
        Quest(id = "declutter-closet", title = "Clear out your closet", description = "Go through your closet and donate everything you haven't worn this year.", category = "Fix", tiers = listOf(QuestTier.MONTHLY), minutes = 90),
        Quest(id = "bake-bread-from-scratch", title = "Bake a loaf from scratch", description = "Make bread from flour, water, and yeast. No bread machine.", category = "Make", tiers = listOf(QuestTier.MONTHLY), minutes = 180),
        Quest(id = "learn-first-aid", title = "Learn basic first aid", description = "Take a first aid or CPR class, in person, from someone who isn't a screen.", category = "Find", tiers = listOf(QuestTier.MONTHLY), minutes = 120),
        Quest(id = "give-blood", title = "Give blood", description = "Donate blood at a local drive or center.", category = "Talk", tiers = listOf(QuestTier.MONTHLY), minutes = 60),
        Quest(id = "town-hall", title = "Go to a town hall meeting", description = "Sit in on a local council or town hall meeting and hear what's actually being decided nearby.", category = "Talk", tiers = listOf(QuestTier.MONTHLY), minutes = 90),
        Quest(id = "animal-shelter", title = "Volunteer at an animal shelter", description = "Spend an afternoon at a shelter walking dogs or cleaning kennels.", category = "Talk", tiers = listOf(QuestTier.MONTHLY), minutes = 180),
        Quest(id = "record-family-story", title = "Record a family story", description = "Sit down with an older relative and record them telling one story from their life.", category = "Talk", tiers = listOf(QuestTier.MONTHLY), minutes = 60),
        Quest(id = "start-garden-bed", title = "Start a garden bed", description = "Dig, plant, and commit to tending a small garden bed for the rest of the month.", category = "Fix", tiers = listOf(QuestTier.MONTHLY), minutes = 120),
        Quest(id = "fruit-picking", title = "Go fruit picking", description = "Find a farm or orchard and pick your own fruit for the afternoon.", category = "Go", tiers = listOf(QuestTier.MONTHLY), minutes = 120),
        Quest(id = "learn-five-birds", title = "Learn five birds by call", description = "Spend the month learning to recognize five local birds by their call alone.", category = "Find", tiers = listOf(QuestTier.MONTHLY), minutes = 0),
        Quest(id = "digital-detox-weekend", title = "A weekend with the phone off", description = "Turn the phone off for a full weekend, not just a day. Tell people first.", category = "Go", tiers = listOf(QuestTier.MONTHLY), minutes = 0),
        Quest(id = "big-repair-project", title = "Fix something that's been broken for months", description = "Pick the broken thing you've been stepping around for months and actually fix it.", category = "Fix", tiers = listOf(QuestTier.MONTHLY), minutes = 120),
        Quest(id = "geocaching", title = "Try geocaching", description = "Find three geocaches near you using nothing but the coordinates.", category = "Find", tiers = listOf(QuestTier.MONTHLY), minutes = 90),
        Quest(id = "solo-hike", title = "Take yourself on a hike", description = "Plan a hike further than you'd usually go, and go alone.", category = "Move", tiers = listOf(QuestTier.MONTHLY), minutes = 180),
        Quest(id = "new-tradition-service", title = "Sit in on a tradition that isn't yours", description = "Attend a religious or cultural service outside your own background, as a respectful guest.", category = "Go", tiers = listOf(QuestTier.MONTHLY), minutes = 90),
        Quest(id = "write-short-story", title = "Write a short story", description = "Write a complete short story this month, start to finish, and share it with one person.", category = "Write", tiers = listOf(QuestTier.MONTHLY), minutes = 0),
        Quest(id = "neighborhood-potluck", title = "Host a potluck for your neighbors", description = "Invite the people on your street over and have everyone bring a dish.", category = "Talk", tiers = listOf(QuestTier.MONTHLY), minutes = 180),
        Quest(id = "month-of-journaling", title = "Keep a journal for the month", description = "Write something by hand every day this month, even one line.", category = "Write", tiers = listOf(QuestTier.MONTHLY), minutes = 0),
        Quest(id = "hold-a-conversation", title = "Hold a conversation in a new language", description = "Learn enough of a language to hold one real conversation, then have it.", category = "Talk", tiers = listOf(QuestTier.MONTHLY), minutes = 30),
        Quest(id = "trail-cleanup", title = "Join a trail or park cleanup", description = "Spend a day picking up litter or clearing brush with a local cleanup group.", category = "Fix", tiers = listOf(QuestTier.MONTHLY), minutes = 180),
        Quest(id = "family-recipe-book", title = "Write down the family recipes", description = "Collect recipes from relatives and write them out by hand in one place.", category = "Write", tiers = listOf(QuestTier.MONTHLY), minutes = 120),
        Quest(id = "silent-day", title = "Go a day without talking", description = "Pick one day and go through it without speaking. Write notes if you need to.", category = "Find", tiers = listOf(QuestTier.MONTHLY), minutes = 0),
        Quest(id = "print-your-photos", title = "Print your photos", description = "Pick twenty photos from your phone this month and get them printed.", category = "Make", tiers = listOf(QuestTier.MONTHLY), minutes = 60),
        Quest(id = "month-long-fast", title = "Give something up for the month", description = "Pick one thing, sugar, alcohol, a habit, and go without it for the whole month.", category = "Find", tiers = listOf(QuestTier.MONTHLY), minutes = 0),
        Quest(id = "car-basics", title = "Learn to check your own oil", description = "Learn to check your oil, change a tire, and jump a battery. Do all three.", category = "Fix", tiers = listOf(QuestTier.MONTHLY), minutes = 45),
        Quest(id = "weekly-kindness", title = "One act of kindness a week", description = "Do something kind for a stranger once a week, every week this month.", category = "Talk", tiers = listOf(QuestTier.MONTHLY), minutes = 0),
        Quest(id = "standing-phone-free-dinner", title = "Start a phone-free dinner tradition", description = "Pick one night a week and make it a standing phone-free dinner, all month.", category = "Talk", tiers = listOf(QuestTier.MONTHLY), minutes = 0),
        Quest(id = "learn-an-instrument-basics", title = "Learn to play something", description = "Learn to play one full song on an instrument you don't already know.", category = "Make", tiers = listOf(QuestTier.MONTHLY), minutes = 0),
        Quest(id = "visit-a-cemetery", title = "Walk an old cemetery", description = "Walk through an old cemetery and read the stones. Notice the dates.", category = "Look", tiers = listOf(QuestTier.MONTHLY), minutes = 60),
        Quest(id = "build-something-from-wood", title = "Build something out of wood", description = "Build one simple thing from wood, a shelf, a box, a stool.", category = "Make", tiers = listOf(QuestTier.MONTHLY), minutes = 180),
        Quest(id = "donate-time-not-money", title = "Give a skill away", description = "Offer a skill you have for free to someone who needs it. No charge.", category = "Talk", tiers = listOf(QuestTier.MONTHLY), minutes = 120),
        Quest(id = "rewatch-childhood-place", title = "Go back to somewhere from your childhood", description = "Go back to a place that mattered to you as a kid and see what's still there.", category = "Go", tiers = listOf(QuestTier.MONTHLY), minutes = 90),
        Quest(id = "declutter-digital-photos", title = "Clear out your camera roll", description = "Go through your phone's camera roll and delete everything you don't need.", category = "Fix", tiers = listOf(QuestTier.MONTHLY), minutes = 45),
    )
}
