[tool]
id = "com.tyshi00.aventura"
label = "Aventura"
versionCode = 7
versionName = "1.3.0"
permissions = []
# Real Light Phone III hardware.
serverPackage = "com.lightos"
# For the Android Studio emulator instead, use:
# serverPackage = "com.thelightphone.sdk.emulator"
