[tool]
id = "com.tyshi00.aventura"
label = "Aventura"
versionCode = 4
versionName = "1.1.2"
permissions = []
# change if you run this on an LP3!
# serverPackage = "com.lightos"
serverPackage = "com.thelightphone.sdk.emulator"
